server:
  http_listen_port: 3200
  log_level: warn

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:14317
        http:
          endpoint: 0.0.0.0:14318

ingester:
  trace_idle_period: 10s
  max_block_bytes: 1_000_000
  max_block_duration: 5m

storage:
  trace:
    backend: local
    local:
      path: /data/tempo/blocks
    wal:
      path: /data/tempo/wal
    pool:
      max_workers: 100
      queue_depth: 10000

metrics_generator:
  registry:
    external_labels:
      source: tempo
      stack: galileo
  storage:
    path: /data/tempo/generator
    remote_write:
      - url: http://localhost:9090/api/v1/write
        send_exemplars: true
  processor:
    service_graphs:
      dimensions:
        - http.method
        - http.url
    span_metrics:
      dimensions:
        - http.method
        - http.url
        - service.name

overrides:
  defaults:
    metrics_generator:
      processors:
        - service-graphs
        - span-metrics